# gpt-3.5 as an example, where the intent analysis is generated by gpt-4.1

import json
import os.path
from tqdm import tqdm
from utils import obtain_response_gpt, obtain_response_qwen
from argparse import ArgumentParser


# parser = ArgumentParser()
# parser.add_argument('--selected', type=str, default='1,2,3,4')
# parser.add_argument('--explanation', type=str, default='gpt')
# args = parser.parse_args()


# selected = args.selected
# selected = selected.split(',')
# selected = [int(_) for _ in selected]
# explanation_name = args.explanation
# assert explanation_name in ['gpt', 'gpt5', 'qwen']


def main():
    with open('../evidence/prompts/evaluate.txt') as f:
        prompt = f.read()
    path = '../misinformation/data'
    dataset_names = os.listdir(path)
    for dataset_name in dataset_names:
        data = json.load(open(f'../misinformation/data/{dataset_name}'))
        evidences = json.load(open(f'../evidence/data/{dataset_name}'))
        # if explanation_name != 'gpt':
        #     explanations = json.load(open(f'explanation_{explanation_name}/{dataset_name}'))
        #     save_path = f'scores_mitigation_gpt5/{explanation_name}_{dataset_name}'
        # else:
        #     explanations = json.load(open(f'explanation/{dataset_name}'))
        #     save_path = f'scores_mitigation_gpt5/gpt41_{dataset_name}'
        explanations = json.load(f'data/{dataset_name}')
        save_path = f'scores/gpt41_{dataset_name}'
        if os.path.exists(save_path):
            out = json.load(open(save_path))
        else:
            out = []
        indices = list(range(len(data)))
        for index in tqdm(indices[len(out):]):
            claim = data[index]
            if claim is None:
                claim = ' '
            each_evidence = evidences[index][3]
            each_explanation = explanations[index]
            evidence_text = ''
            for _, (each, ee) in enumerate(zip(each_evidence, each_explanation)):
                evidence_text += f'{_ + 1}: {each}\n'
                evidence_text += f'Analysis: {ee}\n'
            inputs = prompt.replace('<===c===>', claim)
            inputs = inputs.replace('<===e===>', evidence_text)
            try:
                out.append(obtain_response_gpt(inputs, model='gpt-3.5-turbo'))
            except:
                out.append(' ')
            json.dump(out, open(save_path, 'w'))


if __name__ == '__main__':
    main()

